test

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -15,20 +15,26 @@ making:
     - cd ../grep/
     - make s21_grepp
     - cat ./src/status.txt << 1
+    after_script:
+    - >
+      if [ $CI_JOB_STATUS == 'success' ]; then
+        echo 'This will only run on success'
+      else
+        echo 'This will only run when job failed or is cancelled'
+      fi
   artifacts:
     paths:
       - src/cat/s21_cat
       - src/grep/s21_grep
     expire_in: 30 days
-  allow_failure: true
 
-ci_notify:
-  stage: build
-  when: on_failure
-  script:
-    - bash ./src/tg_bot_notify.sh
-    - exit 1
-  allow_failure: false
+# ci_notify:
+#   stage: build
+#   when: on_failure
+#   script:
+#     - bash ./src/tg_bot_notify.sh
+#     - exit 1
+#   allow_failure: false
 
 checking:
   stage: style
